# Generated by Django 6.0.5 on 2026-05-06 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
